# Generated by Django 5.2.9 on 2026-09-13 10:53

import django_ledger_extensions.models
import django_ledger_extensions.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_ledger_extensions", "0006_entitytaxprofile_invoice_legal_notice"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="accountingreminderrule",
            new_name="django_ledg_entity__001349_idx",
            old_name="django_ledg_entity__b7e4a1_idx",
        ),
        migrations.RenameIndex(
            model_name="documentinboxitem",
            new_name="django_ledg_entity__461f69_idx",
            old_name="django_ledg_entity__a0d1f8_idx",
        ),
        migrations.RenameIndex(
            model_name="documentinboxitem",
            new_name="django_ledg_externa_7e55ad_idx",
            old_name="django_ledg_externa_6a2b0b_idx",
        ),
        migrations.RenameIndex(
            model_name="documentinboxitem",
            new_name="django_ledg_linked__ad2504_idx",
            old_name="django_ledg_linked__fb8d66_idx",
        ),
        migrations.RenameIndex(
            model_name="externalpaymentrecord",
            new_name="django_ledg_entity__df8e98_idx",
            old_name="django_ledg_entity__f8e2d1_idx",
        ),
        migrations.RenameIndex(
            model_name="externalpaymentrecord",
            new_name="django_ledg_status_d4f6b2_idx",
            old_name="django_ledg_status_4c8b2a_idx",
        ),
        migrations.RenameIndex(
            model_name="externalpaymentrecord",
            new_name="django_ledg_record__65c337_idx",
            old_name="django_ledg_record__f3a1c2_idx",
        ),
        migrations.AlterField(
            model_name="documentinboxitem",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("receipt", "Receipt"),
                    ("invoice", "Invoice"),
                    ("bank_statement", "Bank statement"),
                    ("contract", "Contract"),
                    ("other", "Other"),
                ],
                default="receipt",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="documentinboxitem",
            name="file",
            field=models.FileField(
                max_length=512,
                storage=django_ledger_extensions.storage.get_beleg_storage,
                upload_to=django_ledger_extensions.models.document_inbox_upload_to,
            ),
        ),
        migrations.AlterField(
            model_name="supportingdocumentmodel",
            name="file",
            field=models.FileField(
                max_length=512,
                storage=django_ledger_extensions.storage.get_beleg_storage,
                upload_to=django_ledger_extensions.models.supporting_document_upload_to,
            ),
        ),
    ]
